{
    'name': 'License Management',
    'version': '18.0.1.0.0',
    'category': 'Administration',
    'summary': 'Professional annual license management for Odoo Community',
    'description': 'Manage software licenses with expiry, grace periods, online verification, and login blocking.',
    'author': 'Your Company Name',
    'depends': ['base', 'mail', 'web'],
    'data': [
        'security/license_security.xml',
        'security/ir.model.access.csv',
        'data/license_data.xml',
        'data/license_cron.xml',
        'data/license_mail_templates.xml',
        'wizard/license_activate_wizard_views.xml',
        'wizard/license_renew_wizard_views.xml',
        'views/license_management_views.xml',
        'views/res_config_settings_views.xml',
        'views/license_dashboard.xml',
        'views/license_menu.xml',
        'templates/license_expired_page.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'license_management/static/src/js/license_banner.js',
            'license_management/static/src/css/license_styles.css',
            'license_management/static/src/xml/license_templates.xml',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
